### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by ethicalhack3r** [k4ch0w/PwnBack#4]
I love the idea but was wondering how it worked? (without me having to spend hours going through the source code)

1. Do you spider the target site first? Then spider wayback? Then compare the two?
2. Do you just spider wayback and show the links?
3. Do you use Burp's current spider results and compare against wayback findings?

Would be cool if this was elaborated on in the main readme.

Thanks!

**Comment by k4ch0w** [comment]
1. It spiders only Wayback, it will never directly touch the site. I did this to make it completely passive without alerting the target you are looking at it.

2. I spider WayBack for the root page, robots.txt and sitemap.xml and filter the query based on the sha digest in Wayback to prevent extra work. Each one is then parsed and added to the sitemap tree. If you double click each individual element you can see the timestamp of when it was indexed.

3. I don't at the moment. No. The source code itself is pretty simple the hardest part was figuring out how to do Java Swing.

I'll do that soon.
